# Industry Stock Prices

> Comparing average returns on stocks across industries.

In this assignment, we conduct a descriptive analysis of the returns on stocks across industries of S&P 500 companies. To conduct the analysis, we used a dataset from kaggle.com containing information on the S&P 500 companies and their industries. The dataset also contains sub-industries of the companies but we will focus on the main industries (e.g. Health Care, Information Technology, etc.). Additionally, we downloaded data for the stock prices in the year 2023 using Yahoo finance. 

Yfinance has to be installed to run this notebook.

Imports and set magics:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
import seaborn as sns
from datetime import datetime

# Autoreload modules when code is run
%load_ext autoreload
%autoreload 2

# Install yfinance
#pip install yfinance
import yfinance as yf

# user written modules
import dataproject as dp

plt.rcParams.update({"axes.grid":True,"grid.color":"black","grid.alpha":"0.25","grid.linestyle":"--"})
plt.rcParams.update({'font.size': 14})

ModuleNotFoundError: No module named 'dataproject'

# Reading and cleaning data

Import a CSV file that contains S&P 500 companies and their industries.

In [ ]:
# Read file, sort values in alphabetical order and reset index
SP500 = (pd.read_csv('sp500-companies.csv', encoding='ISO-8859-1')
         .sort_values(by=['Ticker'],ascending=True)
         .reset_index(drop=True))

# Drop columns we don't need
drop_columns = ['Sub-Industry', 'Headquarters Location', 'Date added', 'Founded']
SP500.drop(drop_columns, axis=1, inplace=True)

# Remove duplicates
SP500.index.duplicated(keep='first')

# Display dataframe
SP500.head()

  Ticker                     Name                Industry
0      A     Agilent Technologies             Health Care
1    AAL  American Airlines Group             Industrials
2    AAP       Advance Auto Parts  Consumer Discretionary
3   AAPL               Apple Inc.  Information Technology
4   ABBV                   AbbVie             Health Care

Create a list of yfinance tickers to pass as input to yfinance.

In [ ]:
# Create a list of yfinance tickers 
SP500_tickers = list(SP500['Ticker'])

Download data for 2023 from Yahoo finance and extract adjusted close prices. The adjusted close price is the closing price after adjustments for all applicable splits and dividend distributions.

In [ ]:
# Download historical market data for the year 2023
hist_prices = yf.download(tickers = SP500_tickers, start = '2023-01-01',
                        end = '2023-12-31',
                        interval = '1mo')

# Get adjusted close for each stock and change dates
hist_prices = hist_prices['Adj Close']

# Change dateformat
hist_prices.index = pd.to_datetime(hist_prices.index, format='%m-%y')

# Display DataFrame
hist_prices.head()

[*********************100%%**********************]  503 of 503 completed

10 Failed downloads:
['BRK.B', 'ATVI', 'RE', 'DISH', 'ABC', 'FRC', 'PKI', 'CDAY']: Exception('%ticker%: No timezone found, symbol may be delisted')
['BF.B']: Exception('%ticker%: No price data found, symbol may be delisted (1mo 2023-01-01 -> 2023-12-31)')
['PEAK']: Exception('%ticker%: No data found, symbol may be delisted')

Ticker,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACGL,ACN,ADBE,...,WYNN,XEL,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-01,150.738098,16.139999,148.047409,143.305099,139.367401,NaN,107.328476,64.349998,272.630829,370.339996,...,102.589592,65.787468,111.146988,36.091805,102.376045,127.461815,126.122299,316.179993,50.097919,163.157745
2023-02-01,140.717316,15.980000,140.930862,146.403824,146.548462,NaN,99.202927,70.000000,260.502563,323.950012,...,107.271652,61.769627,105.302689,37.306950,101.037407,124.190086,122.685493,300.250000,47.704227,165.033325
2023-03-01,137.119324,14.750000,118.229881,164.024475,151.757172,NaN,98.754311,67.870003,280.377502,385.369995,...,110.775780,64.515152,105.871628,38.492695,103.373146,129.588928,127.964539,318.000000,28.427031,164.479935
2023-04-01,134.235001,13.640000,122.040924,168.779099,143.901260,NaN,107.736412,75.070000,274.962433,377.559998,...,113.121750,67.414871,114.251747,41.242657,102.524048,137.928619,137.377823,288.029999,26.460979,173.709930
2023-05-01,114.836136,14.780000,71.751022,176.308914,132.578430,NaN,99.973129,69.699997,301.283752,417.790009,...,97.699654,62.959755,98.650032,35.527897,98.930176,126.262871,126.362991,262.570007,25.919603,161.436279

Clean the data by removing empty columns.

In [ ]:
# Remove columns with NaN values
hist_prices_clean = hist_prices.dropna(axis=1)

To

In [ ]:
# Calculate monthly and cumulative returns 
monthly_returns, cumulative_returns = dp.calculate_returns(hist_prices_clean)

# Set the first row of the cumulative returns to 1
cumulative_returns.iloc[0] = 1

# Display DataFrame
cumulative_returns.head()

Ticker,A,AAL,AAP,AAPL,ABBV,ABT,ACGL,ACN,ADBE,ADI,...,WYNN,XEL,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-01,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2023-02-01,0.933522,0.990087,0.951931,1.021623,1.051526,0.924293,1.087801,0.955514,0.874737,1.069983,...,1.045639,0.938927,0.947418,1.033668,0.986924,0.974332,0.972750,0.949617,0.952220,1.011495
2023-03-01,0.909653,0.913879,0.798595,1.144582,1.088900,0.920113,1.054701,1.028415,1.040584,1.155525,...,1.079795,0.980660,0.952537,1.066522,1.009740,1.016688,1.014607,1.005756,0.567429,1.008104
2023-04-01,0.890518,0.845105,0.824337,1.177761,1.032532,1.003801,1.166589,1.008552,1.019496,1.053929,...,1.102663,1.024737,1.027934,1.142715,1.001446,1.082117,1.089243,0.910968,0.528185,1.064675
2023-05-01,0.761826,0.915737,0.484649,1.230305,0.951287,0.931469,1.083139,1.105098,1.128126,1.041097,...,0.952335,0.957017,0.887564,0.984376,0.966341,0.990594,1.001908,0.830445,0.517379,0.989449

Create a dictionary of the companies sorted according to their industries.

In [ ]:
# Group companies by sector
grouped_companies = {}
for index, row in SP500.iterrows():
    if row['Industry'] in grouped_companies:
        grouped_companies[row['Industry']].append(row['Ticker'])
    else:
        grouped_companies[row['Industry']] = [row['Ticker']]

print(grouped_companies)

{'Health Care': ['A', 'ABBV', 'ABC', 'ABT', 'ALGN', 'AMGN', 'BAX', 'BDX', 'BIIB', 'BIO', 'BMY', 'BSX', 'CAH', 'CI', 'CNC', 'COO', 'CRL', 'CTLT', 'CVS', 'DGX', 'DHR', 'DVA', 'DXCM', 'ELV', 'EW', 'GEHC', 'GILD', 'HCA', 'HOLX', 'HSIC', 'HUM', 'IDXX', 'ILMN', 'INCY', 'IQV', 'ISRG', 'JNJ', 'LH', 'LLY', 'MCK', 'MDT', 'MOH', 'MRK', 'MRNA', 'MTD', 'OGN', 'PFE', 'PKI', 'PODD', 'REGN', 'RMD', 'STE', 'SYK', 'TECH', 'TFX', 'TMO', 'UHS', 'UNH', 'VRTX', 'VTRS', 'WAT', 'WST', 'XRAY', 'ZBH', 'ZTS'], 'Industrials': ['AAL', 'ALK', 'ALLE', 'AME', 'AOS', 'BA', 'CARR', 'CAT', 'CHRW', 'CMI', 'CPRT', 'CSGP', 'CSX', 'CTAS', 'DAL', 'DE', 'DOV', 'EFX', 'EMR', 'ETN', 'EXPD', 'FAST', 'FDX', 'FTV', 'GD', 'GE', 'GNRC', 'GWW', 'HII', 'HON', 'HWM', 'IEX', 'IR', 'ITW', 'J', 'JBHT', 'JCI', 'LDOS', 'LHX', 'LMT', 'LUV', 'MAS', 'MMM', 'NDSN', 'NOC', 'NSC', 'ODFL', 'OTIS', 'PCAR', 'PH', 'PNR', 'PWR', 'RHI', 'ROK', 'ROL', 'RSG', 'RTX', 'SNA', 'SWK', 'TDG', 'TT', 'TXT', 'UAL', 'UNP', 'UPS', 'URI', 'VRSK', 'WAB', 'WM', 'XYL'], 'Consumer Discretionary': ['AAP', 'AMZN', 'APTV', 'AZO', 'BBWI', 'BBY', 'BKNG', 'BWA', 'CCL', 'CMG', 'CZR', 'DG', 'DHI', 'DLTR', 'DPZ', 'DRI', 'EBAY', 'ETSY', 'EXPE', 'F', 'GM', 'GPC', 'GRMN', 'HAS', 'HD', 'HLT', 'KMX', 'LEN', 'LKQ', 'LOW', 'LVS', 'MAR', 'MCD', 'MGM', 'MHK', 'NCLH', 'NKE', 'NVR', 'NWL', 'ORLY', 'PHM', 'POOL', 'RCL', 'RL', 'ROST', 'SBUX', 'TGT', 'TJX', 'TPR', 'TSCO', 'TSLA', 'ULTA', 'VFC', 'WHR', 'WYNN', 'YUM'], 'Information Technology': ['AAPL', 'ACN', 'ADBE', 'ADI', 'ADP', 'ADSK', 'AKAM', 'AMAT', 'AMD', 'ANET', 'ANSS', 'APH', 'AVGO', 'BR', 'CDAY', 'CDNS', 'CDW', 'CRM', 'CSCO', 'CTSH', 'DXC', 'ENPH', 'EPAM', 'FFIV', 'FIS', 'FISV', 'FLT', 'FSLR', 'FTNT', 'GEN', 'GLW', 'GPN', 'HPE', 'HPQ', 'IBM', 'INTC', 'INTU', 'IT', 'JKHY', 'JNPR', 'KEYS', 'KLAC', 'LRCX', 'MA', 'MCHP', 'MPWR', 'MSFT', 'MSI', 'MU', 'NOW', 'NTAP', 'NVDA', 'NXPI', 'ON', 'ORCL', 'PAYC', 'PAYX', 'PTC', 'PYPL', 'QCOM', 'QRVO', 'ROP', 'SEDG', 'SNPS', 'STX', 'SWKS', 'TDY', 'TEL', 'TER', 'TRMB', 'TXN', 'TYL', 'V', 'VRSN', 'WDC', 'ZBRA'], 'Financials': ['ACGL', 'AFL', 'AIG', 'AIZ', 'AJG', 'ALL', 'AMP', 'AON', 'AXP', 'BAC', 'BEN', 'BK', 'BLK', 'BRK.B', 'BRO', 'C', 'CB', 'CBOE', 'CFG', 'CINF', 'CMA', 'CME', 'COF', 'DFS', 'FDS', 'FITB', 'FRC', 'GL', 'GS', 'HBAN', 'HIG', 'ICE', 'IVZ', 'JPM', 'KEY', 'L', 'LNC', 'MCO', 'MET', 'MKTX', 'MMC', 'MS', 'MSCI', 'MTB', 'NDAQ', 'NTRS', 'PFG', 'PGR', 'PNC', 'PRU', 'RE', 'RF', 'RJF', 'SCHW', 'SPGI', 'STT', 'SYF', 'TFC', 'TROW', 'TRV', 'USB', 'WFC', 'WRB', 'WTW', 'ZION'], 'Consumer Staples': ['ADM', 'BF.B', 'BG', 'CAG', 'CHD', 'CL', 'CLX', 'COST', 'CPB', 'EL', 'GIS', 'HRL', 'HSY', 'K', 'KDP', 'KHC', 'KMB', 'KO', 'KR', 'LW', 'MDLZ', 'MKC', 'MNST', 'MO', 'PEP', 'PG', 'PM', 'SJM', 'STZ', 'SYY', 'TAP', 'TSN', 'WBA', 'WMT'], 'Utilities': ['AEE', 'AEP', 'AES', 'ATO', 'AWK', 'CEG', 'CMS', 'CNP', 'D', 'DTE', 'DUK', 'ED', 'EIX', 'ES', 'ETR', 'EVRG', 'EXC', 'FE', 'LNT', 'NEE', 'NI', 'NRG', 'PCG', 'PEG', 'PNW', 'PPL', 'SO', 'SRE', 'WEC', 'XEL'], 'Materials': ['ALB', 'AMCR', 'APD', 'AVY', 'BALL', 'CE', 'CF', 'CTVA', 'DD', 'DOW', 'ECL', 'EMN', 'FCX', 'FMC', 'IFF', 'IP', 'LIN', 'LYB', 'MLM', 'MOS', 'NEM', 'NUE', 'PKG', 'PPG', 'SEE', 'SHW', 'STLD', 'VMC', 'WRK'], 'Real Estate': ['AMT', 'ARE', 'AVB', 'BXP', 'CBRE', 'CCI', 'CPT', 'DLR', 'EQIX', 'EQR', 'ESS', 'EXR', 'FRT', 'HST', 'INVH', 'IRM', 'KIM', 'MAA', 'O', 'PEAK', 'PLD', 'PSA', 'REG', 'SBAC', 'SPG', 'UDR', 'VICI', 'VTR', 'WELL', 'WY'], 'Energy': ['APA', 'BKR', 'COP', 'CTRA', 'CVX', 'DVN', 'EOG', 'EQT', 'FANG', 'HAL', 'HES', 'KMI', 'MPC', 'MRO', 'OKE', 'OXY', 'PSX', 'PXD', 'SLB', 'TRGP', 'VLO', 'WMB', 'XOM'], 'Communication Services': ['ATVI', 'CHTR', 'CMCSA', 'DIS', 'DISH', 'EA', 'FOX', 'FOXA', 'GOOG', 'GOOGL', 'IPG', 'LUMN', 'LYV', 'META', 'MTCH', 'NFLX', 'NWS', 'NWSA', 'OMC', 'PARA', 'T', 'TMUS', 'TTWO', 'VZ', 'WBD']}

## Exploring the dataset

In order to be able to **explore the raw data**, you may provide **static** and **interactive plots** to show important developments

**Interactive plot** :

In [ ]:
plt.figure(figsize=(10, 6))
for ticker in SP500_tickers:
    plt.plot(hist_prices_clean['Date'], hist_prices_clean['Adj Close'][ticker], label=ticker)
plt.xlabel('Date')
plt.ylabel('Adj Close Price')
plt.title('Stock Prices Over Time')
plt.legend()
plt.show()

KeyError: 'Date'

In [ ]:
industries = grouped_companies.keys()
dropdown = widgets.Dropdown(options = industries, description='Industry:')

def plot_cumulative_returns(industry):
    plt.figure(figsize=(10, 6))
    plt.plot(cumulative_returns.index, cumulative_returns[industry], color='blue', linewidth=2)
    plt.title(f'Cumulative Returns of {industry} Industry')
    plt.xlabel('Date')
    plt.ylabel('Cumulative Returns')
    plt.grid(True)
    plt.show()

# widgets.interact(plot_cumulative_returns, data = widgets.fixed(cumulative_returns), stock = dropdown)
widgets.interact(plot_cumulative_returns, data = widgets.fixed(cumulative_returns), stock = dropdown,
                # Set reference
                ref = widgets.fixed('^OMXC25'),
                # Set figure no.
                fig = widgets.fixed(1),
                # ax_data are only for non-interactive plots
                ax_data=widgets.fixed(None));

ValueError: cannot find widget or abbreviation for argument: 'industry'

Explain what you see when moving elements of the interactive plot around.

# Merge data sets

Merge the data on cumulative returns and the data from the SP500 dataframe.

In [ ]:
merged_data = pd.merge(hist_prices_clean.transpose(), SP500, on='Ticker')
merged_data.head()

,Ticker,2023-01-01 00:00:00,2023-02-01 00:00:00,2023-03-01 00:00:00,2023-04-01 00:00:00,2023-05-01 00:00:00,2023-06-01 00:00:00,2023-07-01 00:00:00,2023-08-01 00:00:00,2023-09-01 00:00:00,2023-10-01 00:00:00,2023-11-01 00:00:00,2023-12-01 00:00:00,Name,Industry
0,A,150.738113,140.717300,137.119339,134.235001,114.836136,119.383118,121.123016,120.426743,111.225891,102.820786,127.377281,138.570129,Agilent Technologies,Health Care
1,AAL,16.139999,15.980000,14.750000,13.640000,14.780000,17.940001,16.750000,14.730000,12.810000,11.150000,12.430000,13.740000,American Airlines Group,Industrials
2,AAP,148.047409,140.930893,118.229881,122.040916,71.751015,69.201500,73.227585,67.984856,55.251274,51.398602,50.419548,60.584858,Advance Auto Parts,Consumer Discretionary
3,AAPL,143.305099,146.403809,164.024475,168.779114,176.308914,193.207016,195.677261,187.130997,170.766830,170.327972,189.458313,192.284637,Apple Inc.,Information Technology
4,ABBV,139.367401,146.548462,151.757156,143.901245,132.578430,129.474411,143.745148,142.793030,144.833466,137.176880,139.737427,152.083069,AbbVie,Health Care

# Analysis

In [ ]:
# window_size = 30
# merged_data['30_day_MA'] = merged_data[]

grouped_returns = merged_data.groupby('Industry')
# print(grouped_returns.head())
# average_returns = grouped_returns['Return'].mean()

print(grouped_returns.describe())

#plt.figure(figsize=(10, 6))
##plt.plot(merged_data['Return'])
#plt.title('Time Series of Daily Returns')
#plt.xlabel('Return')
#plt.ylabel('Frequency')
#plt.grid(True)
#plt.show()

                       2023-01-01 00:00:00                                     \
                                     count        mean         std        min
Industry
Communication Services                23.0   90.228628   98.747641   5.250000
Consumer Discretionary                56.0  338.264742  829.396995  10.820000
Consumer Staples                      33.0  102.470596   92.041748  33.956875
Energy                                23.0   83.780111   53.940541  16.609695
Financials                            62.0  138.348338  134.884938  14.192810
Health Care                           63.0  227.546881  226.403998  11.480914
Industrials                           70.0  165.720935  134.762135  16.139999
Information Technology                74.0  186.131848  132.427938  15.527389
Materials                             29.0  128.160843   93.533538  11.321114
Real Estate                           29.0  129.637331  135.685380  17.742973
Utilities                             30.0   67.724069   31.100453  15.881371

                                                                        \
                              25%         50%         75%          max
Industry
Communication Services  26.721520   54.119999  110.683784   384.309998
Consumer Discretionary  57.091166  115.407906  172.300594  5270.000000
Consumer Staples        49.529049   73.132568  124.012650   494.497009
Energy                  36.076321   63.796593  124.593281   213.596176
Financials              52.060211   95.388103  164.380527   733.382812
Health Care             81.880001  176.059998  278.525009  1532.920044
Industrials             68.108419  122.508118  218.806267   692.296570
Information Technology  76.487001  157.568237  263.032505   569.566040
Materials               55.609634  107.344429  166.389496   356.767639
Real Estate             51.866291  105.622063  152.330688   720.193298
Utilities               43.017464   65.497459   87.983419   152.547424

                       2023-02-01 00:00:00              ...  \
                                     count        mean  ...
Industry                                                ...
Communication Services                23.0   85.540227  ...
Consumer Discretionary                56.0  332.618892  ...
Consumer Staples                      33.0  100.040332  ...
Energy                                23.0   77.279103  ...
Financials                            62.0  133.175654  ...
Health Care                           63.0  217.959122  ...
Industrials                           70.0  165.932673  ...
Information Technology                74.0  183.036486  ...
Materials                             29.0  123.686296  ...
Real Estate                           29.0  122.481684  ...
Utilities                             30.0   63.497455  ...

                       2023-11-01 00:00:00              2023-12-01 00:00:00  \
                                       75%          max               count
Industry
Communication Services          135.777557   473.970001                23.0
Consumer Discretionary          174.655094  6155.390137                56.0
Consumer Staples                108.379219   576.724060                33.0
Energy                          125.107513   226.013382                23.0
Financials                      176.538185   741.648010                62.0
Health Care                     273.035614  1091.930054                63.0
Industrials                     230.073040   928.723938                70.0
Information Technology          269.499992   917.584961                74.0
Materials                       168.982468   463.252899                29.0
Real Estate                     127.315102   806.522949                29.0
Utilities                        80.883976   130.326691                30.0

                                                                       \
                              mean          std        min        25%
Industry
Communication Services  110.231127   130.783329   1.830000  26.502798
Consumer Discretionary  410.412087  1098.173987   8.597445  49.556267
Consumer Staples        101.512147   109.585524  25.817156  52.177841
Energy                   85.186825    55.982077  17.085064  35.565081
Financials              146.685930   148.232648  12.421221  52.033358
Health Care             229.324268   211.688050  10.724598  78.482079
Industrials             195.949963   178.832149  13.740000  82.248257
Information Technology  236.040456   207.670717  16.725145  90.670414
Materials               134.121909   117.415331   9.508162  47.779419
Real Estate             132.519149   147.900608  18.847795  56.083435
Utilities                65.370054    30.167699  18.008877  47.339914


                               50%         75%          max
Industry
Communication Services   43.240612  140.309998   486.880005
Consumer Discretionary  128.330814  189.975380  7000.450195
Consumer Staples         71.543404  119.162758   643.423218
Energy                   68.391281  130.602287   222.432220
Financials               96.754414  184.259945   801.445435
Health Care             155.558899  297.393494  1212.959961
Industrials             141.435783  245.980492  1011.599976
Information Technology  170.097580  293.657494  1106.428711
Materials                88.233665  173.028809   498.270935
Real Estate              97.226822  138.782898   801.480652
Utilities                60.528156   82.528835   131.227280

[11 rows x 96 columns]

To get a quick overview of the data, we show some **summary statistics** on a meaningful aggregation.

MAKE FURTHER ANALYSIS. EXPLAIN THE CODE BRIEFLY AND SUMMARIZE THE RESULTS.

# Conclusion

ADD CONCISE CONLUSION.